<?php

namespace AppBundle\Repository;

/**
 * PlayBigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayBigRepository extends \Doctrine\ORM\EntityRepository
{
}
