<?php

namespace AppBundle\Repository;

/**
 * PlaySmallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaySmallRepository extends \Doctrine\ORM\EntityRepository
{
}
