landing:
    resource: "@LandingBundle/Resources/config/routing.yml"

pinpong:
    resource: "@PinPongBundle/Resources/config/routing.yml"
    prefix: /wooppay

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
